# Generated by Django 4.1 on 2022-09-15 10:52

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='static/images/avatar_dummy.png', upload_to='user_avatar')),
                ('bio', models.TextField(blank=True, default='')),
                ('instrument', models.CharField(blank=True, default='', max_length=255)),
                ('music_style', models.CharField(blank=True, default='', max_length=255, verbose_name='musical styles')),
                ('equipment', models.TextField(blank=True, default='')),
                ('is_mobile', models.BooleanField(default=False)),
                ('cut', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('rate', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
