# Generated by Django 4.1 on 2022-09-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='rate',
            new_name='rating',
        ),
    ]
