# Generated by Django 4.1 on 2022-09-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_rate_userprofile_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('-rating',)},
        ),
    ]
