# Generated by Django 4.1 on 2022-09-19 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('instrument', models.CharField(max_length=200)),
                ('music_style', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cut', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cut_unit', models.CharField(choices=[(1, 'hour'), (2, 'song'), (3, 'concert'), (4, 'session')], default=1, max_length=200)),
                ('event_start', models.DateTimeField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-added',),
            },
        ),
        migrations.CreateModel(
            name='StudioSession',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jobs.job')),
                ('location', models.CharField(default='Remote', max_length=200)),
                ('studio_name', models.CharField(blank=True, default='', max_length=200)),
            ],
            bases=('jobs.job',),
        ),
    ]
