# Generated by Django 4.1 on 2022-12-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_tour_days_off'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={},
        ),
        migrations.AddField(
            model_name='jobaccess',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
