# Generated by Django 4.1 on 2023-03-05 18:41

from django.db import migrations


def generate_job_cut_units(apps, schema_editor):
    CutUnit = apps.get_model('jobs', 'CutUnit')
    CutUnit.objects.bulk_create(
        [
            CutUnit(name='hour'),
            CutUnit(name='song'),
            CutUnit(name='concert'),
            CutUnit(name='session'),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_cutunit_alter_job_cut_unit'),
    ]

    operations = [
        migrations.RunPython(generate_job_cut_units)
    ]
